name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13, 14]
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.0.0
      with:
        node-version: ${{ matrix.node }}
    - name: Install
      run: npm install
    - name: Test
      run: npm test

  publish:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.0.0
      with:
        node-version: 10
    - name: npm login
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Publish artifacts
      run: npm publish
